### ISSUE TITLE
DIVE Desktop Export of TrackJSON as CSV file [FEATURE]

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#509] opened 2020-12-20 11:54 UTC
Part of the project based system for DIVE Desktop will require being able to export trackJSON data as CSV files.

Going to add to the viame serializer the ability to take a trackJSON datafile and export it as a VIAME CSV file.  I'll base it on the same structure used in the web backend.  If I have additional time, I'll add the same tests used on the backend.

**Comment by subdavis** [comment] 2021-01-12 13:34
Duplicate of #493

**Closed by subdavis** 2021-01-12 13:34 UTC
Labels: enhancement
